"""init

Revision ID: 0e4109772e93
Revises:
Create Date: 2025-01-28 22:18:02.463576

"""

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "0e4109772e93"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user_subcription",
        sa.Column("user_id", sa.String(), nullable=False),
        sa.Column("subcription_id", sa.String(), nullable=False),
        sa.Column(
            "start_date",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("end_date", sa.DateTime(), nullable=False),
        sa.Column("photo_by_promnt_count", sa.Integer(), nullable=False),
        sa.Column("photo_by_image_count", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("user_id", name=op.f("user_subcription_pkey")),
    )
    op.create_table(
        "users",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("nickname", sa.String(length=1000), nullable=False),
        sa.Column("tg_premium", sa.Boolean(), nullable=False),
        sa.Column(
            "user_type",
            sa.Enum("CUSTOMER", "VIP", "WHITELISTED", name="usertype"),
            nullable=False,
        ),
        sa.Column("models_max", sa.Integer(), nullable=False),
        sa.Column(
            "started_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("users_pkey")),
    )
    op.create_table(
        "models",
        sa.Column("id", sa.Integer(), sa.Identity(always=False), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("user_id", sa.String(), nullable=False),
        sa.Column("gender", sa.Enum("MALE", "FEMALE", name="gender"), nullable=False),
        sa.Column("link_to_adls", sa.String(), nullable=True),
        sa.Column(
            "status",
            sa.Enum("TRAIN_STARTED", "READY", name="modelstatus"),
            nullable=False,
        ),
        sa.Column("photo_info", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("models_pkey")),
    )
    op.create_table(
        "subcriptions",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("title", sa.String(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("cost", sa.Integer(), nullable=False),
        sa.Column("duration", sa.Integer(), nullable=False),
        sa.Column("photo_by_prompt_limit", sa.Integer(), nullable=False),
        sa.Column("photo_by_image_limit", sa.Integer(), nullable=False),
        sa.Column("started_at", sa.DateTime(), nullable=False),
        sa.Column("ended_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("subcriptions_pkey")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("subcriptions")
    op.drop_table("models")
    op.drop_table("users")
    op.drop_table("user_subcription")
    # ### end Alembic commands ###
