"""add_users

Revision ID: 4bdd56cc4d1e
Revises:
Create Date: 2025-01-26 23:18:16.986968

"""

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "4bdd56cc4d1e"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("nickname", sa.String(length=1000), nullable=False),
        sa.Column("tg_premium", sa.Boolean(), nullable=True),
        sa.Column(
            "user_type",
            sa.Enum("CUSTOMER", "VIP", "WHITELISTED", name="usertype"),
            nullable=False,
        ),
        sa.Column(
            "started_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("users_pkey")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("users")
    # ### end Alembic commands ###
